---
- name: Test output
  command: echo 'hello world'
- name: Create apps directory
  file: 
     path: /apps
     state: directory
- name: Copy Apache archive to destination
  copy:
     src: ../files/apache.tar.gz
     dest: /apps/
- name: Unpack Apache archive
  command: tar xvzf /apps/apache.tar.gz
- name: Delete Apache archive on destination
  file:
     src: /apps/apache.tar.gz
     state: absent
